apiVersion: v1
kind: PersistentVolume
metadata:
  name: sample-pv
  annotations:
    volumeType: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
